# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('男', 'male'), ('女', 'female')], max_length=1)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
    ]
