# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=4)),
                ('age', models.DateField()),
                ('professional', models.CharField(choices=[('english', '英语'), ('chinese', '汉语')], max_length=20)),
                ('nation', models.CharField(choices=[('han', '汉族'), ('hui', '回族'), ('man', '满族')], max_length=20)),
                ('nation_place', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=20)),
                ('describe', models.TextField()),
                ('contact_infor', models.IntegerField()),
            ],
        ),
    ]
